# Generated by Django 5.2.17 on 2026-08-22 23:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DIET', 'Diet'), ('ORIGIN', 'Origin'), ('SEASONALITY', 'Seasonality'), ('CERTIFICATION', 'Certification')], max_length=20)),
            ],
            options={
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('package_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('measured_in', models.CharField(choices=[('PIECE', 'Piece'), ('GRAM', 'Gram'), ('KILOGRAM', 'Kilogram'), ('MILLILITRE', 'Millilitre'), ('LITRE', 'Litre')], max_length=20)),
                ('sold_in', models.CharField(choices=[('TUBE', 'Tube'), ('BOTTLE', 'Bottle'), ('BAG', 'Bag'), ('BOX', 'Box'), ('CAN', 'Can'), ('PACKAGE', 'Package'), ('PIECE', 'Piece')], max_length=20)),
                ('purchase_price_per_package', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('CHF', 'Swiss Franc')], default='CHF', max_length=3)),
            ],
            options={
                'ordering': ['article_number'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preferences', models.ManyToManyField(blank=True, related_name='recipes', to='event_in_a_box.preference')),
                ('supported_event_types', models.ManyToManyField(blank=True, related_name='recipes', to='event_in_a_box.eventtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_guest', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='event_in_a_box.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='event_in_a_box.recipe')),
            ],
            options={
                'ordering': ['recipe', 'product'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'product'), name='unique_recipe_product')],
            },
        ),
    ]
